In [1]:
import pandas as pd
import numpy as np
import os
import yaml

In [2]:
# --- Load Configuration ---
with open('config.yml', 'r') as f:
    config = yaml.safe_load(f)

# --- Use the config values ---
DATA_ROOT = os.path.expanduser(config['paths']['data_root'])
MANIFEST_FILE = config['paths']['manifest_file'].format(data_root=DATA_ROOT)

In [3]:
manifest = pd.read_csv(MANIFEST_FILE)

In [4]:
manifest.columns

Index(['horse_name', 'email_date', 'message_id', 'original_filename',
       'filename', 'date_added', 'canonical_id', 'num_horses_detected',
       'status'],
      dtype='object')

In [5]:
manifest['original_canonical_id'] = manifest['canonical_id']
manifest['last_merged_timestamp'] = pd.NA  # Initialize with NA

In [6]:
manifest

,horse_name,email_date,message_id,original_filename,filename,date_added,canonical_id,num_horses_detected,status,original_canonical_id,last_merged_timestamp
0,Guinness,20241023,197501aef3e81a5e,IMG_0847.jpg,197501aef3e81a5e-IMG_0847.jpg,2025-06-09,1,NaN,NaN,1,<NA>
1,Guinness,20241023,197501aef3e81a5e,IMG_0848.jpg,197501aef3e81a5e-IMG_0848.jpg,2025-06-09,1,NaN,NaN,1,<NA>
2,Guinness,20241023,197501aef3e81a5e,IMG_0849.jpg,197501aef3e81a5e-IMG_0849.jpg,2025-06-09,1,NaN,NaN,1,<NA>
3,Guinness,20241023,197501aef3e81a5e,IMG_0850.jpg,197501aef3e81a5e-IMG_0850.jpg,2025-06-09,1,NaN,NaN,1,<NA>
4,Guinness,20241023,197501aef3e81a5e,IMG_0851.jpg,197501aef3e81a5e-IMG_0851.jpg,2025-06-09,1,NaN,NaN,1,<NA>
...,...,...,...,...,...,...,...,...,...,...,...
1836,Oliver,20241029,197178e6155b1fbb,IMG_2726.jpg,197178e6155b1fbb-IMG_2726.jpg,2025-06-09,235,NaN,NaN,235,<NA>
1837,Oliver,20241029,197178e6155b1fbb,IMG_2727.jpg,197178e6155b1fbb-IMG_2727.jpg,2025-06-09,235,NaN,NaN,235,<NA>
1838,Oliver,20241029,197178e6155b1fbb,IMG_2728.jpg,197178e6155b1fbb-IMG_2728.jpg,2025-06-09,235,NaN,NaN,235,<NA>
1839,Oliver,20241029,197178e6155b1fbb,IMG_2729.jpg,197178e6155b1fbb-IMG_2729.jpg,2025-06-09,235,NaN,NaN,235,<NA>
1840,Oliver,20241029,197178e6155b1fbb,IMG_2730.jpg,197178e6155b1fbb-IMG_2730.jpg,2025-06-09,235,NaN,NaN,235,<NA>

In [8]:
manifest.columns

Index(['horse_name', 'email_date', 'message_id', 'original_filename',
       'filename', 'date_added', 'canonical_id', 'num_horses_detected',
       'status', 'original_canonical_id', 'last_merged_timestamp'],
      dtype='object')

In [10]:
manifest.to_csv(MANIFEST_FILE, index=False, 
                columns=['canonical_id','original_canonical_id','horse_name', 'email_date', 'message_id', 'original_filename',
       'filename', 'date_added',  'num_horses_detected',
       'last_merged_timestamp', 'status'],
                na_rep='')