In [11]:
import pandas as pd
import numpy as np
import os

In [12]:
DATA_ROOT = os.environ.get('HORSE_ID_DATA_ROOT', '%s/google-drive/horseID Project/data' % os.environ.get('HOME', '.'))
MANIFEST_FILE = '%s/horse_photos_manifest.csv' % DATA_ROOT

In [13]:
manifest = pd.read_csv(MANIFEST_FILE)

In [16]:
manifest

,horse_name,email_date,message_id,filename,date_added,status,is_ambiguous
0,Al,20250522,1973b8e512a9e9e1,Al-20250522-1973b8e512a9e9e1-IMG_5202.jpg,2025-06-05,NaN,NaN
1,Al,20250522,1973b8e512a9e9e1,Al-20250522-1973b8e512a9e9e1-IMG_5203.jpg,2025-06-05,NaN,NaN
2,Al,20250522,1973b8e512a9e9e1,Al-20250522-1973b8e512a9e9e1-IMG_5204.jpg,2025-06-05,NaN,NaN
3,Al,20250522,1973b8e512a9e9e1,Al-20250522-1973b8e512a9e9e1-IMG_5205.jpg,2025-06-05,NaN,NaN
4,Angie,20250528,1971c6c807b75195,Angie-20250528-1971c6c807b75195-IMG_6273.jpg,2025-06-05,NaN,NaN
...,...,...,...,...,...,...,...
935,Zora,20250528,1971c65602eda5b9,Zora-20250528-1971c65602eda5b9-IMG_6570.jpg,2025-06-05,NaN,NaN
936,Zora,20250528,1971c65602eda5b9,Zora-20250528-1971c65602eda5b9-IMG_6571.jpg,2025-06-05,NaN,NaN
937,Zora,20250528,1971c65602eda5b9,Zora-20250528-1971c65602eda5b9-IMG_6573.jpg,2025-06-05,NaN,NaN
938,Zora,20250528,1971c65602eda5b9,Zora-20250528-1971c65602eda5b9-IMG_6575.jpg,2025-06-05,NaN,NaN
939,Zora,20250528,1971c65602eda5b9,Zora-20250528-1971c65602eda5b9-IMG_6577.jpg,2025-06-05,NaN,NaN

In [ ]:
manifest.to_csv(MANIFEST_FILE, index=False, 
                columns=['horse_name','email_date','message_id','filename','date_added','multi_horse_detected','status'],
                na_rep='')